name: pubs
author: Günter Zöchbauer <guenter@gzoechbauer.com>
homepage: http://github.com/zoechi/pubs
version: 0.1.0
environment:
  sdk: '>=1.9.0 <2.0.0'
description: Automate Dart build and deploy tasks.
dependencies:
  browser: any
  packages_file:
#    git: https://github.com/lrhn/dep-pkgspec.git/packages_file
    path: ../dart-lang/dep-pkgspec/packages_file
  test: '^0.12.1'
executables:
  pubs:

dev_dependencies:
  grinder: '^0.7.1+1'
