name: pubs
author: Günter Zöchbauer <guenter@gzoechbauer.com>
homepage: http://github.com/zoechi/pubs
version: 0.1.0
environment:
  sdk: '>=1.9.0 <2.0.0'
description: Automate Dart build and deploy tasks.
dependencies:

  analyzer: '^0.25.0+1'
  package_config:
    git: https://github.com/dart-lang/package_config.git
  test: '^0.12.1'
  path: '^1.3.5'
  archive: '^1.0.19'
  cli_util: '^0.0.1+2'

executables:
  pubs:

dev_dependencies:
  grinder: '^0.7.1+1'
