name: pubs
author: Günter Zöchbauer <guenter@gzoechbauer.com>
homepage: http://github.com/bwu-dart/pubs
version: 0.1.1+5
environment:
  sdk: '>=1.9.0 <2.0.0'
description: Automate Dart build and deploy tasks.

dependencies:
  analyzer: '^0.25.0+1'
  ansicolor: '^0.0.9'
  archive: '^1.0.19'
  cli_util: '^0.0.1+2'
  package_config:
    git: https://github.com/dart-lang/package_config.git
  path: '^1.3.5'
  unscripted: '^0.6.1+1'

dev_dependencies:
  test: '^0.12.1'
  grinder: '^0.7.1+1'

executables:
  pubs:
